baseURL = "https://fantasyalgo.github.io/PortfolioSite/"
languageCode = "en-us"
title = "Avery portfolio"
theme = "portfolio"
publishDir = "docs"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[params]
name = "Avery"
tagline = "About"
articlesTagline = "Thoughts on game development, programming, and technology"
about = """
<p>
Hi, I’m Avery, a game developer who likes making things from scratch to really understand how they work. I’ve used all kinds of technologies across my projects, so I’m comfortable adapting to whatever a job needs.
</p> 
"""

  [[params.personalInfo]]
  label = "Age"
  value = "18"

  [[params.personalInfo]]
  label = "Languages"
  value = "English (Ielts 7.5), Italian (mother tongue)"

  [[params.personalInfo]]
  label = "Location"
  value = "Rome, RM, Italy"

  [[params.social]]
  icon = "fa-brands fa-github"
  url = "https://github.com/fantasyAlgo"

  [[params.projects]]
  title = "Moon lander 3d"
  description = "A 3d game made completely in webgl and typescript without libraries"
  image = "images/MoonLanderPhoto.jpeg"
  url = "https://github.com/fantasyAlgo/Moon_lander_3d"

  [[params.projects]]
  title = "Minecraft clone"
  description = "A simple minecraft clone made in c++ opengl with world generation and saving, with a ton of optimizations!"
  image = "images/minecraft_clone.png"
  url = "https://github.com/fantasyAlgo/openglMinicraft"

  [[params.projects]]
  title = "Infinite doppelganger"
  description = "A demo of a UDP-based multiplayer MMO, made with python3 and raylib"
  image = "images/infiniteDoppleganger.png"
  url = "/articles/idoppelganger/"

  [[params.projects]]
  title = "Moon lander game"
  description = "A canvas JS game where you need to land in procedurally generated terrain"
  image = "images/moon_lander.jpeg"
  url = "https://github.com/fantasyAlgo/Moon-lander"

  [[params.projects]]
  title = "2D physics engine"
  description = "A 2d physics engine with everything you need to make a game"
  image = "images/moonPhysicsEngine.png"
  url = "https://github.com/fantasyAlgo/moonPhysicsEngine"

  [[params.projects]]
  title = "2D Fluid simulation"
  description = "An SPH-based fluid simulation inspired by sebastian lague's video"
  image = "images/fluidSim.png"
  url = "https://github.com/fantasyAlgo/RayFluidSPH"

  [[params.projects]]
  title = "Terraria clone"
  description = "A demo of a terraria clone made in c++ with raylib"
  image = "images/terraria_clone.png"
  url = "https://github.com/fantasyAlgo/TerrariaCloneRefactor"

  [[params.projects]]
  title = "Pacman clone"
  description = "A copy of pacman in c++ SFML"
  image = "images/pacman_clone.png"
  url = "https://github.com/fantasyAlgo/Fake_pacman"



  [[params.projects]]
  title = "Asteroid game"
  description = "Asteroid but better, made using Java JFrame with no external libraries!"
  image = "images/asteroids.jpeg"
  url = "https://github.com/fantasyAlgo/JFrameAsteroids"



  [[params.small_projects]]
  title = "Rubik's cube simulator"
  description = "A simple rubik's cube playground made in threejs"
  image = "images/rubik_cube.png"
  url = "https://github.com/fantasyAlgo/Threejs-rubik-cube"

  [[params.small_projects]]
  title = "AstarMaze"
  description = "A simple maze generator with an Astar pathfinder"
  image = "images/AstarDemo.png"
  url = "https://github.com/fantasyAlgo/AstarMaze"



  [[params.contact]]
  icon = "fas fa-envelope"
  title = "Email"
  value = "averyLikesOpengl@gmail.com"

  [[params.contact]]
  icon = "fas fa-phone"
  title = "Phone"
  value = "+39 392 749 8905"

  [[params.contact]]
  icon = "fas fa-map-marker-alt"
  title = "Location"
  value = "Rome, Italy"

